### ISSUE TITLE
Fatal error in initialization with cocos2d-x-3.12 in Android

### ISSUE THREAD

**Issue by attekei** [soomla/cocos2dx-store#194]
Seems that this library is not actively maintained anymore, but I report anyway a bug with newest versions of cocos2d-x. Seems that when calling `soomla::CCSoomlaStore::initialize`, some class is missing somewhere. The stack trace is not super helpful because it only says that `java.lang.NoClassDefFoundError` error is thrown but I don't which class (or then I'm just not able to interpret the stack trace). 

The funny thing with this issue is that I wanted to ask this in http://answers.soom.la, but I couldn't create an account to the forum (lol), because seems that server was down or something.  So here we go:

```
08-11 16:50:42.424 4498-4576/com.Seeds.IosTestApp E/art: JNI GetStringUTFChars called with pending exception 'java.lang.NoClassDefFoundError' thrown in unknown throw location
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70] JNI DETECTED ERROR IN APPLICATION: GetStringUTFChars received null jstring
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]     in call to GetStringUTFChars
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]     from void org.cocos2dx.lib.Cocos2dxRenderer.nativeTouchesEnd(int, float, float)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70] "GLThread 188" prio=5 tid=21 Runnable
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   | group="main" sCount=0 dsCount=0 obj=0x12dae090 self=0xab6fe6c0
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   | sysTid=4576 nice=0 cgrp=default sched=0/0 handle=0xe352f000
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   | state=R schedstat=( 1235143840 61855696 860 ) utm=112 stm=11 core=0 HZ=100
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   | stack=0xe342d000-0xe342f000 stackSize=1036KB
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   | held mutexes= "mutator lock"(shared held)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #00 pc 00004db0  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #01 pc 00244081  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+68)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #02 pc 002297ad  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+144)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #03 pc 000b026d  /system/lib/libart.so (art::JniAbort(char const*, char const*)+556)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #04 pc 000b0985  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+60)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #05 pc 000b22e3  /system/lib/libart.so (art::ScopedCheck::CheckInstance(art::ScopedCheck::InstanceKind, _jobject*)+334)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #06 pc 000b2dc9  /system/lib/libart.so (art::ScopedCheck::Check(bool, char const*, ...) (.constprop.141)+744)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #07 pc 000bb805  /system/lib/libart.so (art::CheckJNI::GetStringUTFChars(_JNIEnv*, _jstring*, unsigned char*)+44)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #08 pc 004046b9  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (_JNIEnv::GetStringUTFChars(_jstring*, unsigned char*)+28)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #09 pc 004049cd  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (soomla::CCNdkBridge::callNative(cocos2d::__Dictionary*, soomla::CCError**)+412)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #10 pc 004064e9  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (soomla::CCSoomla::initialize(char const*)+352)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #11 pc 003db0ef  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (InAppStore::init()+114)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #12 pc 003dafd1  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (InAppStore::create()+84)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #13 pc 003db03b  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (InAppStore::createScene()+14)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #14 pc 003da2c7  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (HelloWorld::labelClickCallback(cocos2d::Ref*)+10)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #15 pc 003dae1b  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (void std::_Mem_fn<void (HelloWorld::*)(cocos2d::Ref*)>::operator()<cocos2d::Ref*, void>(HelloWorld*, cocos2d::Ref*&&) const+78)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #16 pc 003dad15  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (void std::_Bind<std::_Mem_fn<void (HelloWorld::*)(cocos2d::Ref*)> (HelloWorld*, std::_Placeholder<1>)>::__call<void, cocos2d::Ref*&&, 0u, 1u>(std::tuple<cocos2d::Ref*&&>&&, std::_Index_tuple<0u, 1u>)+92)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #17 pc 003daa99  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (void std::_Bind<std::_Mem_fn<void (HelloWorld::*)(cocos2d::Ref*)> (HelloWorld*, std::_Placeholder<1>)>::operator()<cocos2d::Ref*, void>(cocos2d::Ref*&&)+56)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #18 pc 003da8cb  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (std::_Function_handler<void (cocos2d::Ref*), std::_Bind<std::_Mem_fn<void (HelloWorld::*)(cocos2d::Ref*)> (HelloWorld*, std::_Placeholder<1>)> >::_M_invoke(std::_Any_data const&, cocos2d::Ref*)+34)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #19 pc 0044dd89  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (std::function<void (cocos2d::Ref*)>::operator()(cocos2d::Ref*) const+48)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #20 pc 0044a925  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (cocos2d::MenuItem::activate()+64)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #21 pc 0044b0bd  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (cocos2d::MenuItemLabel::activate()+52)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #22 pc 00445929  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (cocos2d::Menu::onTouchEnded(cocos2d::Touch*, cocos2d::Event*)+208)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #23 pc 00449cb3  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (void std::_Mem_fn<void (cocos2d::Menu::*)(cocos2d::Touch*, cocos2d::Event*)>::operator()<cocos2d::Touch*, cocos2d::Event*, void>(cocos2d::Menu*, cocos2d::Touch*&&, cocos2d::Event*&&) const+94)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #24 pc 00449891  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (void std::_Bind<std::_Mem_fn<void (cocos2d::Menu::*)(cocos2d::Touch*, cocos2d::Event*)> (cocos2d::Menu*, std::_Placeholder<1>, std::_Placeholder<2>)>::__call<void, cocos2d::Touch*&&, cocos2d::Event*&&, 0u, 1u, 2u>(std::tuple<cocos2d::Touch*&&, cocos2d::Event*&&>&&, std::_Index_tuple<0u, 1u, 2u>)+120)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #25 pc 0044912d  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (void std::_Bind<std::_Mem_fn<void (cocos2d::Menu::*)(cocos2d::Touch*, cocos2d::Event*)> (cocos2d::Menu*, std::_Placeholder<1>, std::_Placeholder<2>)>::operator()<cocos2d::Touch*, cocos2d::Event*, void>(cocos2d::Touch*&&, cocos2d::Event*&&)+68)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #26 pc 004487c7  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (std::_Function_handler<void (cocos2d::Touch*, cocos2d::Event*), std::_Bind<std::_Mem_fn<void (cocos2d::Menu::*)(cocos2d::Touch*, cocos2d::Event*)> (cocos2d::Menu*, std::_Placeholder<1>, std::_Placeholder<2>)> >::_M_invoke(std::_Any_data const&, cocos2d::Touch*, cocos2d::Event*)+50)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #27 pc 004ee1d7  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (std::function<void (cocos2d::Touch*, cocos2d::Event*)>::operator()(cocos2d::Touch*, cocos2d::Event*) const+66)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #28 pc 004eb07f  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (???)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #29 pc 004f072d  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (???)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #30 pc 004edc89  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (std::function<bool (cocos2d::EventListener*)>::operator()(cocos2d::EventListener*) const+48)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #31 pc 004eaa93  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (cocos2d::EventDispatcher::dispatchTouchEventToListeners(cocos2d::EventDispatcher::EventListenerVector*, std::function<bool (cocos2d::EventListener*)> const&)+870)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #32 pc 004eb655  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (cocos2d::EventDispatcher::dispatchTouchEvent(cocos2d::EventTouch*)+388)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #33 pc 004eacb1  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (cocos2d::EventDispatcher::dispatchEvent(cocos2d::Event*)+92)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #34 pc 004b6bd3  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (cocos2d::GLView::handleTouchesOfEndOrCancel(cocos2d::EventTouch::EventCode, int, int*, float*, float*)+598)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #35 pc 004b6ce3  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (cocos2d::GLView::handleTouchesEnd(int, int*, float*, float*)+34)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #36 pc 0041ce79  /data/app/com.Seeds.IosTestApp-1/lib/arm/libMyGame.so (Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeTouchesEnd+68)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   native: #37 pc 00078bdf  /data/data/com.Seeds.IosTestApp/cache/slice-slice_1-classes.dex (Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeTouchesEnd__IFF+102)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   at org.cocos2dx.lib.Cocos2dxRenderer.nativeTouchesEnd(Native method)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   at org.cocos2dx.lib.Cocos2dxRenderer.handleActionUp(Cocos2dxRenderer.java:128)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   at org.cocos2dx.lib.Cocos2dxGLSurfaceView$9.run(Cocos2dxGLSurfaceView.java:277)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1509)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70]   at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)
08-11 16:50:42.487 4498-4576/com.Seeds.IosTestApp A/art: art/runtime/check_jni.cc:70] 
08-11 16:50:42.488 4498-4576/com.Seeds.IosTestApp A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 4576 (GLThread 188)
```

**Comment by enrevol** [comment]
Do you compile keeva-1.0.1.jar?

**Comment by attekei** [comment]
@enrevol Nope, wasn't mentioned in [Instructions for Android](https://github.com/soomla/cocos2dx-store#instructions-for-android)

**Comment by enrevol** [comment]
If you use the latest version of Soomla, you need to compile it.
The instructions are not up-to-date.

**Comment by attekei** [comment]
Ok! For me this was (luckily) only a test project, so I don't really have a need to use cocos2dx-store anymore. But hopefully this issue is helpful for some others that still want to give cocos2dx-store a try :)
